pkgxdev/pkgx

src/app.exec.ts
Only zsh permits the long `--interactive` argument. Tested against:
* bash
* dash
* csh
* zsh
Fixes https://github.com/teaxyz/cli/issues/119.
=> Fix interactive shell argument

README.md, src/hooks/useDownload.ts, tests/unit/cache.test.ts
Storing Etag received from `fetch` API parallel to mtime file and passing this header to `If-None-Match`. 
Fixing https://github.com/teaxyz/cli/issues/85
=> Store etag So Downloads Use Cache

src/app.exec.ts, src/hooks/useDownload.ts
Add a few cases to support `bash` and `sh`. We can't pass `--norc` and `--noprofile` to `sh` since those are GNU-isms.
=> support bash for tea shell

src/app.dump.ts, src/hooks/useDownload.ts
Thanks for tea, loving it so far! Here's a few quick fixes for fish I encountered:
- Command not found function is called [fish_command_not_found](https://fishshell.com/docs/current/cmds/fish_command_not_found.html)
- Lists are [1-indexed](https://fishshell.com/docs/current/language.html?highlight=List+indices+start#lists)
- Unquote `"$argv"` to prevent `tea` from intrepreting all arguments as the command (currently fails with `tea: command not found: [ "node --version" ]`)
Also added an extra newline for formatting.
Before:
```fish
function command_not_found_handler
switch "$argv[0]"    case wget; tea '+gnu.org/wget' "$argv"
case node; tea '+nodejs.org' "$argv"
end
end
```
After:
```fish
function fish_command_not_found
switch "$argv[1]"
case wget; tea '+gnu.org/wget' $argv
case node; tea …
```
=> fix(dump): update fish command-not-found

src/app.dump.ts, src/app.exec.ts, src/hooks/usePantry.ts, src/hooks/useShellEnv.ts
Allow specifying env vars to be set at runtime in pantry configs.
Example:
```yaml
runtime:
env:
DENO_NO_UPDATE_CHECK: "true"
```
Updates #26
=> Add runtime environment variables configuration

src/hooks/useVirtualEnv.ts
I think this does it. I'm at a loss for a test for it for the moment. `tea` doesn't seem to throw a version key for me.
```sh
$ tea -X deno run -A --import-map=import-map.json src/app.ts -Ed
set -gx SRCROOT '/Users/jacob/Work/Tea/pantry.core';
set -gx PATH '/Users/jacob/.tea/deno.land/v1.28.2/bin:/Users/jacob/.tea/deno.land/v1.28.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin';
set -gx MANPATH '/opt/homebrew/share/man:/usr/share/man:/usr/local/share/man:/Library/TeX/Distributions/.DefaultTeX/Contents/Man:/opt/homebrew/share/man:';
set -gx LDFLAGS '-Wl,-rpath,/Users/jacob/.tea';
set -gx TEA_PREFIX '/Users/jacob/.tea';
if functions --query fish_command_not_found; functions --erase fish_command_not_found; end
set -gx TEA_REWIND '{"PATH":["/Users/jacob/.tea/deno.land/v1.28.2/bin","/usr/loc …
```
=> use version file

src/hooks/useLogger.ts
I don't know if this is the best way to do it, but it certainly is *a* way to do it. I think it is somewhat elegant that it does not need to modify the behavior of any other files.
ref: https://github.com/teaxyz/cli/issues/3
=> fix: Outputting color codes on non-tty

.github/workflows/cd.yml
obviously don't want to release just to test it; but we can roll it back if it's no good.
=> use mikepenz/release-changelog-builder-action for release changelogs

.gitpod.yml
Get `./tea` with a single click.
**Click Me:** https://gitpod.io/#https://github.com/teaxyz/cli/pull/127
This downloads `deno` for compiling `tea` into `.deno/` in current dir, because Gitpod doesn't persist $HOME when initializing.
```
Deno was installed successfully to .deno/bin/deno
```
Then it compiles `./tea` using README instructons, but doesn't install it.
```
Download ⠋ https://deno.land/x/rimbu@0.12.3/sorted/map-custom/implementation/immutable.tsCheck file:///workspace/teaxyz-cli/src/app.ts
Download ⠸ https://deno.land/x/rimbu@0.12.3/sorted/map-custom/implementation/immutable.ts                                 Compile file:///workspace/teaxyz-cli/src/app.ts
Emit ./tea
./tea is hot
```
Running `./tea` without arguments fails for some reason.
```
$ ./tea
error: Uncaught (in …
```
=> Tea served by Gitpod

README.md, src/app.X.ts, src/app.exec.ts, src/hooks/useFlags.ts, tests/integration/tea-XX.test.ts
=> allow versioned symlinks

import-map.json, src/hooks/useDownload.ts, src/hooks/useExec.ts, src/vendor/Path.ts
This is needed for https://github.com/teaxyz/pantry.core/pull/102 to land.
Marking this as a draft because there's one bit of code that doesn't have a clear transition path to the current standard library (since they removed `std/hash` in favor of the webcrypto api). Currently talking to the deno folks on how to best approach this.
=> chore: bump deno std to latest

.gitignore, src/app.help.ts, src/app.provides.ts, src/app.ts, src/hooks/useExec.ts, src/hooks/useFlags.ts
- `--provides` allows other programs like autocomplete to detect whether a program is available
Many people user terminals that automatically color the commandline depending on whether the program is available or not
This shaky gif demonstrates that (tea breaks vhs a bit)
`tea --provides [packages]` allows programs like `fish` to poll tea before highlighting commands which should lead to a better UX
=> Add `--provides` mode

.github/workflows/cd.yml, .github/workflows/ci.yml, README.md, deno.jsonc, src/app.dump.ts, src/app.help.ts, src/app.magic.ts, src/app.ts, src/hooks/index.ts, src/hooks/useExec.ts, src/hooks/useFlags.ts, src/hooks/useLogger.ts, src/hooks/useShellEnv.ts, src/hooks/useVersion.ts, src/utils/index.ts, src/utils/pkg.ts
`env` but with packaging.
`tea [+pkg]` by default now outputs like `env`. Previously it would start a “REPL”. You can still start a REPL with `tea +pkg sh` which is thus more idiomatic: tea now has no special modes, it installs packages, constructs an environment for them and either outputs envdata or executes cmds.
Typing `tea` when inside a dev-env now outputs the env, again: this is more idiomatic.
These patches also fix a number of conditions where the env was not present although its presence was expected. With 0.21 generally speaking if you type a command inside a dev-env the dependencies that project needs will install if necessary and be available to that command.
=> `tea` is `env++`

.github/workflows/cd.yml
resolves https://github.com/teaxyz/setup/issues/122
If we don't want to fail if CI does (but then what?), set `wait-for-completion: false` on the `smoke-setup:` job's single step.
=> test fire teaxyz/setup:ci.yml

import-map.json, src/hooks/useDownload.ts
Sorry about waiting so long to do this easy PR. I have been relatively busy this week and technically I am still busy but I felt bad about promising to do this and not following through.
Theoretically closes #338
=> fix: using memory proportional to download size

src/hooks/useVirtualEnv.ts
When a deno configuration file didnt't have a tea section listed, tea would panic when sourcing the local environment.
Error: bad-yaml
at usePackageYAML (file:///opt/tea.xyz/src-v0.24.3/src/hooks/usePackageYAML.ts:9:37)
at refineFrontMatter (file:///opt/tea.xyz/src-v0.24.3/src/hooks/usePackageYAML.ts:30:16)
at supp (file:///opt/tea.xyz/src-v0.24.3/src/hooks/useVirtualEnv.ts:109:20)
at async default (file:///opt/tea.xyz/src-v0.24.3/src/hooks/useVirtualEnv.ts:24:13)
at async file:///opt/tea.xyz/src-v0.24.3/src/app.ts:24:21
Fixes https://github.com/teaxyz/cli/issues/384, specifically: https://github.com/teaxyz/cli/issues/384#issuecomment-1434593366
=> fixes a panic:bad-yaml when deno.jsonc doesn't have tea dependencies

src/utils/index.ts, src/vendor/Path.ts
https://github.com/denoland/deno/pull/17340
fixes #405
=> move variants added to Deno.build.os on v1.31.0

.github/workflows/cd.yml
resolves #376
This should be correct, but the test-task (which can be removed) won't run due to a bug that seems to have cropped up between setup and cli (https://github.com/teaxyz/setup/issues/142).
I don't really want to blind-merge it without testing.
=> sign binaries on darwin

.github/workflows/ci.yml, .gitignore, README.md
Adding test coverage with coveralls.io.  Coverage is only counted for the ubuntu tests.  
fixes #324
=> Issue#324 - add test coverage

src/hooks/index.ts, src/hooks/useDownload.ts, src/hooks/useFetch.ts, src/hooks/useGitHubAPI.ts, src/hooks/useInventory.ts, src/prefab/install.ts
I created a useFetch hook that wraps the Deno `fetch` function and automatically adds a `User-Agent` header to the request.
The header looks like `User-Agent: tea.cli/0.24.9`
=> Add user-agent header

src/app.magic.ts
=> fish string built-in: `match` not `contains`.

src/app.magic.ts
Magic currently fails on bash 3.2 (the default version of bash that ships with macOS).
This is due to a [bug in bash 3.2 related to sourcing from a process substitution.](https://lists.gnu.org/archive/html/bug-bash/2006-01/msg00018.html)
This is a known workaround that will work for bash 3.x and newer versions.
Note that although this fixes the sourcing issue, there are other issues with magic when running bash 3.2 (`command_not_found_handler` doesn't work)
Closes #450
=> fix magic for bash

tests/integration/magic.test.ts
Fish doesn't have an equivalent of bash's `set -e` so even though it fails to source tea's magic, the script continues to run. 
There isn't a great way to detect an error when sourcing a fish script because the exit code of `source` is only for the last command run.  I added a check in the test for anything going to stderr that wasn't from tea to help catch syntax errors.
Unfortunately as I needed to check both stderr and stdout I also refactored the integration test suite so that the exit code, stdout, and stderr are always available.  This change is actually the bulk of the PR.
=> Integration tests should catch fish syntax errors

scripts/run_coverage.sh
Now that `lcov` is packaged this script can be updated to use tea
=> coverage script should use tea

src/init.ts
Dev envs were not correctly restricting tea packages to the correct versions because of this typo.
=> TEA_PKGS is not read correctly

src/hooks/index.ts, src/hooks/useDarkMagic.ts, src/hooks/useExec.ts, tests/functional/provides.test.ts
picked the easiest one first
- if no other resolution fails, query `registry.npmjs.org`
- if that finds a package, return `["npx", "-q"]` as the shebang
- hookify it all to make extension simple
- use `Promise.all` to parallelize the search
=> dark magic v0

README.md
docs(README): document Deno bug
Summary:
Reference blockers for quickly developing tea.
https://github.com/denoland/deno/issues/11547 and
https://github.com/denoland/deno/issues/18631
=> docs(README): document Deno bug

src/utils/semver.ts, tests/unit/semver.test.ts
ref: https://github.com/teaxyz/cli/issues/473#issuecomment-1498925758
ref: https://github.com/jhheider/semverator/commit/7d8ae450a5a2af91256c99273797cf9eed0948c1
=> fix behavior of `^` in pre-1.0 semver

import-map.json, src/hooks/useExec.ts, src/vendor/PathUtils.ts, src/vendor/README.md, tests/unit/path-utils.test.ts
if this is out-of-scope, feel free to close. felt like a _common_ path function, on par with `home()`.
=> `PathUtils.ts`: search and manage `$PATH`

src/hooks/useDarkMagic.ts, src/hooks/useExec.ts, tests/functional/provides.test.ts
this uses `Path.findBin()` to test for a `brew` install (we should package brew, probably). If that PR is rejected, then we'll need a new plan.
=> dark magic v0.3.0: brew

src/hooks/usePantry.ts
Allows for platform whitelisting in pantry.
=> add `usePantry().available()`

src/utils/semver.ts, tests/unit/semver.test.ts
Uploaded bottles versions are always checked with Semver with tolerant=true.
Therefore, CLI also has to accept SemVer objects with tolerant=true, I think it meens that tolerant option doesn't be needed.
This PR remove the tolerant option from SemVer.
I confirmed local tests are all passed and tmux=3.3a can be run.
<details>
<summary>test resulsts</summary>
```sh
$ deno task test
Task test deno test --allow-net --allow-read --allow-env --allow-run --allow-write --unstable
Check file:///home/uesyn/src/github.com/uesyn/cli/tests/functional/args.test.ts
Check file:///home/uesyn/src/github.com/uesyn/cli/tests/functional/devenv.test.ts
Check file:///home/uesyn/src/github.com/uesyn/cli/tests/functional/exec.test.ts
Check file:///home/uesyn/src/github.com/uesyn/cli/tests/functional/magic.test.ts …
```
=> Remove tolerant option from Semver

.github/workflows/cd.yml
Resolve  #575 
Update `.github/workflows/cd.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo "::set-output name=result::cancel"
```
```yml
echo "::set-output name=result::commence"
```
**TO-BE**
```yml
echo "result=cancel" >> $GITHUB_OUTPUT;;
```
```yml
echo "result=commence" >> $GITHUB_OUTPUT;;
```
=> Replace deprecated command with environment file

src/app.help.ts
The current verbose help has this list of flags:
```
flags:
[...]
--dry-run,-n             don’t do anything, just print
[...]
--dry-run,-n             don’t execute, just print
```
Which has the `--dry-run` flag duplicated. This commit removes the second instance. Since the wording was slightly different for each of the instances, I kept the wording and the ordering as is used for the "less verbose" version of `--help`, which looks like:
```
flags:
--sync,-S       sync and update environment packages
--env,-E        inject local environment
--dry-run,-n    don’t do anything, just print
```
=> Typo: remove duplicated --dry-run in --help

src/app.main.ts, src/app.provides.ts, src/hooks/index.ts, src/hooks/useConfig.ts, src/hooks/useVersion.ts, src/hooks/useVirtualEnv.ts, src/hooks/useYAMLFrontMatter.ts, src/prefab/install.ts, src/prefab/setup.ts, tests/functional/run.test.ts, tests/integration/tea.ln.test.ts
it’s always symlinked to v* so it can only be the latest version. This suits what most people want this feature for.
Refs #600
=> auto symlink ~/.tea/local/bin/foo on installs

src/app.help.ts
In `tea --help`, "an containerized" shuould be "a containerized".
Thx to @rohanssrao for finding the typo!
=> tea help typo: fix "an containerized"

.vscode/settings.json, src/app.complete.ts, src/app.help.ts, src/app.magic.ts, src/app.main.ts, src/args.ts, tests/functional/run.test.ts
This works. The places I think it might need love:
- it will be slow. and ever slower. useSync should cache all the provides to the sqlite store for much faster performance.
- ~it wasn't in any way clear to me how to interleave our completions with zsh's defaults. possibly because we don't work like anything else~
- ~one possibility is to do the path scanning ourselves, so we can just do the whole completion stack. this will also take time, and want for caching.~
=> zsh autocomplete

src/utils/execve.ts, tests/integration/tea.scripts.test.ts
We need the actual buffer size, instead of string length. Slower, but otherwise we risk truncating input.
Example of failure in action: https://github.com/teaxyz/pantry/actions/runs/5506185252/jobs/10042047292
stage.ts is copying from a non-existent unpack directory, resulting in no source. see also the tarball ending in `tar.g`.
=> fix UTF-8 cli args to exec

.github/workflows/cd.yml
Proof of function: https://github.com/teaxyz/cli/actions/runs/5502595335
closes #633
=> GPG sign binaries; include pubkey in srcs

src/utils/execve.ts
closes #645
there's a `FIXME` for an edge case, but you'd have to be some kind of sicko pervert to have someone else's home directory in your `$PATH`.
=> handles literal ~ in $PATH

README.md, src/app.magic.ts, src/app.main.ts
I don't like the ergonomics of `--magic=install` but it was quick n’ easy. Will revise when I have better ideas
=> tea --magic=install; tea --magic=uninstall

src/hooks/useVirtualEnv.ts
closes #651
complies with: [Finally, you can just use tea.yaml (or .tea.yaml) if you like.](https://docs.tea.xyz/features/developer-environments).
=> allow .tea.yaml/yml per the docs

src/app.exec.ts
Fixes: https://github.com/teaxyz/gui/issues/771
The consistent use of backticks matches what is present in the README (https://github.com/teaxyz/cli/blob/main/README.md?plain=1#L152)
=> Fixing exit prompt formatting

.github/workflows/ci.shellcode.yml, src/modes/shellcode.ts
=> Don’t allow dev to be activate twice

src/app.ts, src/modes/help.ts, src/modes/internal.activate.test.ts, src/modes/internal.activate.ts, src/modes/internal.use.test.ts, src/modes/internal.use.ts, src/modes/repl.ts, src/modes/shellcode.ts, src/utils/InstallLogger.ts, src/utils/Logger.ts, src/utils/color.test.ts, src/utils/color.ts
Also fixes some omissions in dev-env handling
Fixes #712
=> Fix unsetting PS1

docs/dev.md
The first codeblock in the `dev` docs had an extra backtick at the end. This PR just removes it
=> Fix small typo in `dev` docs

docs/faq.md
... since the URL returns a 301 with "Moved Permanently" HTML without the https.
Of course, I'm sure we'd prefer if the DNS got fixed and we don't need to type the full "https://" and we can throw this away.
=> fix one-liner command

.github/Dockerfile, .github/workflows/ci.docker.yaml, docs/SUMMARY.md, docs/faq.md, docs/run/anywhere/docker.md, src/modes/shellcode.ts
=> Update Dockerfile and docker docs

docs/faq.md, docs/run/anywhere/docker.md, docs/running-anything.md, src/app.ts, src/modes/x.test.ts, src/modes/x.ts, src/parse-args.test.ts, src/parse-args.ts
This allows `pkgx +brewkit -- pkg build` to work as well as using system utilities without full paths
=> `pkgx +foo -- bar` should search `bar` in `PATH`

.github/workflows/ci.shellcode.yml, src/modes/shellcode.ts
Note that this doesn’t change the behavior of the command not found handler, that should be a separate more involved fix.
=> Only define `x` if available; Refs #857

fixtures/cdk.json, src/utils/devenv.test.ts, src/utils/devenv.ts
This addresses #883 
If _cdk.json_ exists in the folder, `dev` will install the AWS CDK CLI.
=> Adds cdk.json to devenv list

src/prefab/construct-env.test.ts, src/prefab/construct-env.ts
Refs https://github.com/pkgxdev/pantry/pull/147
=> Trailing colons in env breaks things

src/prefab/construct-env.test.ts, src/prefab/construct-env.ts
=> fix `Assertion failed: pkgx: env is being duped` when multiple unicodes in env

src/modes/install.ts
I noticed this problem when trying to uninstall Python:
Obviously, the source problem is something else that should be fixed. But nevertheless, the stubs should be protected. There may exist some real program name with spaces as well, for example.
=> Escape spaces in stubs for uninstallation

src/modes/internal.activate.ts, src/modes/shellcode.ts
Which was previously throwing _pkgx_dev_off not found.
And also make sure to pass rm -f as some people alias rm to rm -i, which can come from the popular OMZ common-aliases: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/common-aliases#file-handling
=> Fix dev off when environment is not active

src/modes/install.ts
This is just a quick take on #998.
Ideally, pkgx should be able to handle this case by first uninstalling the existing package and then installing the desired one, which would in turn make scripting with pkgx a lot easier.
=> Error when a different version is already installed

src/prefab/construct-env.ts
=> fix regression in construct-env.ts

.github/workflows/cd.yml, .github/workflows/ci.shellcode.yml, .github/workflows/ci.yml, deno.jsonc
Here are some good reasons to upgrade to newest Deno:
1. Deno 2.1 is (or will be) the first ever LTS version of Deno
2. 7% speedier?
Simple Bash script I'm using to benchmark this:
```bash
#!/bin/bash
set -euxo pipefail
hyperfine_jobs=()
for v in 2.0.6 2.1.0; do
deno clean
deno upgrade $v
deno task compile
mv pkgx pkgx-deno-$v
hyperfine_jobs+=("./pkgx-deno-$v git@2.44.0 --version")
done
exec pkgx hyperfine --warmup 2 --shell none --runs 50 "${hyperfine_jobs[@]}"
```
=> Upgrade Deno from v2.0.2 to v2.1.4

.github/workflows/cd.crates.yml
```yaml
- uses: katyo/publish-crates@v2
with:
args: --package pkgx --all-features
registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
```
=> publish pkgx to crates.io

crates/lib/src/env.rs
=> this fixes subprogs missing keys

docs/scripting.md
=> docs for python scripting update 

crates/lib/src/config.rs, docs/faq.md
=> Use XDG_DATA_HOME on *nix if no ~/.pkgx

src/modes/install.ts
Closes https://github.com/pkgxdev/pkgm/issues/6
=> v1: uninstall if needed during install

crates/cli/src/main.rs, crates/lib/src/env.rs
If the runtime env does not recurse its key, parent env overrides.
Eg. SSL_CERT_FILE={{prefix}}, if the parent env sets SSL_CERT_FILE then it persists.
Most runtime env recurses, eg. PYTHONPATH={{prefix}}/lib/python:$PYTHONPATH, and in such cases the parent env is inserted (this is unchanged behavior).
Fixes #1101
=> parent env can override pantry runtime env

.github/workflows/ci.yml, crates/cli/src/main.rs, crates/lib/src/sync.rs
We assume if the user sets PKGX_PANTRY_DIR that they are managing its updates themselves.
=> If PKGX_PANTRY_DIR is set, don’t blow it away

.github/workflows/ci.yml, Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/main.rs, crates/lib/Cargo.toml, crates/lib/src/config.rs, crates/lib/src/sync.rs
This change was thoughtless and accidental. It means we can end up with pkgx^1 and pkgx^2 getting out of sync.
=> Clone pantry to same location as pkgx^1

.github/workflows/ci.yml, Cargo.lock
This reverts commit b20b3f1511412062d3632e66709554c460dcf2f1.
The ca-cert embed worked, but then started failing when I bumped the deps. This was not caught in CI because the CI for the PR ran against `main` that didn't have the bump in it and the bump ran against main that didn't have the embed in it.
lol!
CI did [actually catch it](https://github.com/pkgxdev/pkgx/actions/runs/13319566842/job/37201556550) when it ran against the merge of the PR, but there is no mechanism to communicate that to anyone (nice).
Thus I released 2.3.0 and the embed doesn’t work.
`cd` does run “smoke tests” against `pkgx` before deploying. These tests are not run in a minimal container, so nothing failed.
Nice sequence for failure here.
=> Revert "Bump rusqlite, update rest within constraints"

crates/lib/src/client.rs
Allow differentiation for our CI/CD.
=> Add User-Agent
