pkgxdev/pkgx

src/app.exec.ts

allow `fish` REPL

---

.github/workflows/ci.yml
.markdownlint.yml
README.md
src/prefab/README.md
src/vendor/README.md

I don't know if this better or not, but it makes my VSCode markdownlint plugin stop complaining about these mostly stylistic choices

markdownlint README.md (deeply optional)

---

.github/workflows/ci.yml
README.md
src/app.dump.ts
src/app.exec.ts
src/app.sync.ts
src/app.ts
src/hooks/index.ts
src/hooks/useRequirementsFile.ts
src/hooks/useSync.ts
src/hooks/useVirtualEnv.ts
src/prefab/install.ts
src/prefab/resolve.ts
src/utils/error.ts

not merging until coverage on these pieces is higher.
Shame we have no automated code-coverage :(

More careful code for all of `-x` mode

---

src/app.exec.ts

Fixes CI issues, eg: https://github.com/teaxyz/setup/pull/77

oh good, more complexity

---

README.md
src/app.exec.ts
src/hooks/useMoustaches.ts
src/hooks/usePantry.ts
src/vendor/Path.ts
tests/integration/tea-x.test.ts
tests/utils.ts

Fixes https://github.com/teaxyz/demos/issues/7

Don’t double up args

---

src/app.exec.ts
src/hooks/usePantry.ts

Goes with your app.exec.ts rewrite, @mxcl.
Requires https://github.com/teaxyz/pantry.core/pull/33

move interpreter detection to package.yml

---

src/hooks/useFlags.ts

This includes PR https://github.com/teaxyz/cli/pull/190 and so that PR should probably be closed. IDK.
Anyway, I guess this implements https://github.com/teaxyz/cli/issues/167. It was easier than I thought (because you already added tea_foo).

Issue 167 arg0 magic

---

src/vendor/Path.ts

I was just trying to familiarize myself with the code and found this. My first contribution!

fix: typo in comments of Path

---

README.md

See https://github.com/teaxyz/cli/actions/runs/3572232657/jobs/6004889608

Fix an unused link reference definition in README.md

---

.github/workflows/cd.yml
README.md

Uploads binaries to `www` on release. Includes cleanup of some dead env and a lint fix that was failing.

upload bins to www on release

---

src/prefab/install.ts

Don’t unquarantine

---

src/app.exec.ts
src/hooks/useCellar.ts
src/prefab/link.ts
src/utils/error.ts
src/utils/hacks.ts
src/utils/index.ts
src/utils/safe-utils.ts
src/utils/semver.ts
tests/unit/pkgutils.test.ts
tests/unit/semver.test.ts

not finished as semver-intersect needs more work

arbitrary digit & openssl scheme version support

---

README.md

- twitter
- discord
- tea/cli version

docs: add social badges

---

src/app.magic.ts

Fix fish magic script on v0.19.0

---

.github/workflows/ci.yml
README.md
src/hooks/useExec.ts

Don’t attempt to fopen directories

---

.github/workflows/cd.yml

this isn't fully-automated, since it only opens a remote PR, but it's a good start.

bump teaxyz/homebrew-pkgs/tea-cli on release

---

src/app.magic.ts

It broke again. Perhaps a good idea to set up CI for it as discussed in the previous PR (#300). I'd do it myself if I had more time but I'm currently swamped with my day job.

Fix fish magic

---

README.md
src/app.magic.ts

Gracefully be part of existing zsh stacks

---

src/app.err-handler.ts
src/hooks/useInventory.ts
src/utils/error.ts

Show which pkg we didn’t pkg

---

README.md
src/prefab/install.ts

extract tarballs to tmp directory for atomicity

---

src/prefab/install.ts

fixes https://github.com/teaxyz/cli/issues/420

fix unarchiver stripComponents

---

README.md

Preview: https://github.com/revolter/cli/blob/c55b5ed0868ebfed696bef75ac9ea4c60b51ff3c/README.md#what-are-these---etc-symbols

Add link that actually explains ^ and ~ symbols

---

src/app.dump.ts
src/app.ts

Fixes https://github.com/teaxyz/pantry/issues/823

Prevent `TEA_PKGS=' '` from breaking everything

---

src/prefab/install.ts

delete tarball on ⌃C

---

tests/functional/args.test.ts

This PR adds tests to prevent the regression of the bug fixed by #494

Add tests for collectEnv

---

src/hooks/useDarkMagic.ts
src/hooks/useExec.ts
src/hooks/usePrefix.ts
src/types.ts
tests/functional/provides.test.ts

this is messy; but all other PMs will mostly work this way. so, we should get it right. but, this works at least. let's fight about better ways.

dark magic v0.2.0: cargo

---

import-map.json
src/hooks/index.ts
src/hooks/useDarkMagic.ts
src/hooks/useDb.ts
src/vendor/Path.ts
tests/unit/useDb.test.ts

@mxcl this is a fun one. fundamental direction being implemented here. thoughts more than welcome.

dark magic v0.5.0: persistent user state

---

README.md
src/args.ts
src/hooks/useConfig.ts
src/hooks/useDownload.ts
src/hooks/useErrorHandler.ts
src/hooks/useExec.ts
src/init.ts
src/prefab/install.ts
src/utils/index.ts
tests/integration.suite.ts
tests/integration/cli.test.ts
tests/unit/cache.test.ts

This isn’t all encompassing, but it’s enough for <<REDACTED>>

Dash dash json

---

src/utils/semver.ts
tests/unit/semver.test.ts

fix semver.Range.toString for `>=0.47<1`

---

src/hooks/useVirtualEnv.ts
tests/functional/devenv.test.ts

Tolerate `v` prefix for `.node-version`

---

src/hooks/useDownload.ts
src/hooks/useErrorHandler.ts
src/hooks/useExec.ts
src/hooks/useLogger.ts
src/prefab/install.ts

The JSON flag was not actually printing valid parsable JSON.

fix json output

---

src/hooks/useSync.ts
tests/functional/sync.test.ts

this is a vastly simplified file now too.

failsafe if the git on mac is broken

---

src/hooks/useConfig.ts
src/init.ts
src/prefab/install.ts

feat: TEA_MAGIC=prompt

---

src/hooks/useConfig.ts
tests/unit/useConfig.test.ts

Refs https://github.com/teaxyz/setup/pull/155

restore tea finds prefix if properly installed

---

src/args.ts

lowercase linked arg0s

---

.github/workflows/ci.yml
deno.jsonc
src/app.exec.ts
src/app.magic.ts
src/app.main.ts
src/hooks/index.ts
src/hooks/useErrorHandler.ts
src/hooks/useLogger.ts
src/hooks/useRun.ts
src/hooks/useVersion.ts
src/hooks/useVirtualEnv.ts
src/hooks/useYAMLFrontMatter.ts
src/prefab/install.ts
src/prefab/setup.ts
src/utils/execve.ts
tests/functional/exec.test.ts
tests/functional/repl.test.ts
tests/functional/script.test.ts
tests/functional/suggestions.test.ts
tests/functional/testUtils.ts
tests/integration/cli.test.ts
tests/integration/tea.scripts.test.ts
tests/unit/useErrorHandler.test.ts

implement execle with ffi

---

README.md
deno.jsonc
src/app.main.ts
tests/functional/run.test.ts

This so brew install mechanism works on first use for user

if no pantry and installing, sync

---

src/app.magic.ts

add $TEA_PREFIX/.local/bin on fish

---

fixtures/action.yml/not-node/action.yml
src/utils/devenv.test.ts
src/utils/devenv.ts

handle action.yml without node

---

src/modes/internal.activate.ts
src/modes/internal.use.ts

disable PS1 mangling

---

deno.jsonc

bump deps (libpkgx especially)

---

src/utils/devenv.ts

Add support for .terraform-version file format for dev command

---

src/utils/devenv.test.ts
src/utils/devenv.ts

Sanitize input from env nodes in devenvs

---

src/modes/internal.activate.test.ts
src/modes/internal.activate.ts

Handle setting eg. PATH in devenv better

---

deno.jsonc
src/modes/internal.activate.test.ts
src/utils/devenv.test.ts
src/utils/devenv.ts

[dev] Support symlinked keyfiles

---

docs/run/anywhere/terminals.md

Adds options for `pkgx` and `pkgx-git` AUR packages.

feat(docs): Add AUR installation options

---

tea.yaml

Participate in tea Protocol

---

docs/running-anything.md

just close endhint key

---

src/utils/devenv.ts

Added support for https://github.com/casey/just justfiles

feat(dev): added support for justfiles

---

src/utils/devenv.ts

Add taskfile.dev to environment

feat: added detection of Taskfile.yml via dev

---

.github/workflows/ci.yml
crates/cli/src/args.rs
crates/cli/src/help.rs
crates/cli/src/main.rs

Prevents “resolving…” message flash if you want that in eg. scripts

`pkgx --quiet` suppresses resolving message

---

src/modes/install.ts

fix(install): fix unsafe install script (args passing)

---

Cargo.lock
crates/cli/Cargo.toml
crates/lib/Cargo.toml
crates/lib/src/pantry_db.rs

Fix resync

---

Cargo.lock
crates/lib/Cargo.toml
crates/lib/src/install.rs

Install to tmpdir then atomic move

---

README.md

I was clicking things and found a broken thing, so I fixed it. 
Cheers!

Update link in README for hydrate.rs

---

.github/workflows/ci.yml
crates/cli/src/args.rs
crates/cli/src/main.rs

--shebang, -!

---

.github/workflows/ci.yml
README.md
crates/cli/src/args.rs
crates/cli/src/main.rs
crates/cli/src/query.rs
crates/cli/src/setup.rs

--query,-Q

---

.github/workflows/cd.yml

Relevant conversation: https://github.com/rust-lang/rust/issues/29527

attempt to statically link libgcc on linux
